-- RFC4 | MOSTRAR LOS ALOJAMIENTOS DISPONIBLES EN UN RANGO DE FECHAS, QUE CUMPLEN CON UN CONJUNTO DE REQUERIMIENTOS SERVICIOS
SELECT A_ALOJAMIENTO.ID ID_0, A_ALOJAMIENTO.UBICACION UBICACION, A_ALOJAMIENTO.COSTO COSTO
FROM ((A_ALOJAMIENTO LEFT JOIN A_RESERVA ON A_ALOJAMIENTO.ID = A_RESERVA.IDALOJAMIENTO)
    LEFT JOIN A_ALOJAMIENTOSERVICIO ON A_ALOJAMIENTOSERVICIO.IDALOJAMIENTO = A_ALOJAMIENTO.ID)
    LEFT JOIN A_SERVICIO ON A_ALOJAMIENTOSERVICIO.IDSERVICIO = A_SERVICIO.ID
WHERE A_SERVICIO.TIPO = 'tvCable'
GROUP BY A_ALOJAMIENTO.ID,UBICACION, A_ALOJAMIENTO.COSTO, FECHAINI, FECHAFIN
HAVING COALESCE(A_RESERVA.FECHAINI ,TO_DATE('11-11-1111', 'DD-MM-YYYY')) NOT BETWEEN '05/05/2020' AND '04/04/2021'
    AND COALESCE(A_RESERVA.FECHAFIN ,TO_DATE('11-11-1111', 'DD-MM-YYYY')) NOT BETWEEN '05/05/2020' AND '04/04/2021';