SELECT *
FROM A_ALOJAMIENTO
LEFT JOIN A_RESERVA ON A_ALOJAMIENTO.ID = A_RESERVA.IDALOJAMIENTO
WHERE ((
            (A_RESERVA.FECHAINI NOT BETWEEN ADD_MONTHS(SYSDATE, -1) AND SYSDATE)   
            AND 
            (A_RESERVA.FECHAFIN NOT BETWEEN ADD_MONTHS(SYSDATE, -1) AND SYSDATE)
        )
        OR (A_RESERVA.FECHAINI IS NULL)
        OR (A_RESERVA.ESTADO = 'N'))
        AND (A_ALOJAMIENTO.ESTATUS = 'Y');  