SELECT NOM_TCOLUM, COALESCE(NumColumnas,0) AS NUMCOLUMS, COALESCE(NumColsNull,0) AS NUMCOLSNULL, COALESCE(NumColsFks,0) AS NUMCOLSFKS 
FROM((SELECT TABLE_NAME AS NOM_TCOLUM, COUNT(TABLE_NAME) AS NumColumnas 
     FROM ALL_TAB_COLUMNS 
     WHERE owner = 'PARRANDEROS' 
     GROUP BY TABLE_NAME) LEFT OUTER JOIN 
     (SELECT TABLE_NAME AS NOM_TNULL, COUNT(NULLABLE) AS NumColsNull 
     FROM ALL_TAB_COLUMNS 
     WHERE owner = 'PARRANDEROS' AND NULLABLE = 'Y' 
     GROUP BY TABLE_NAME) ON NOM_TCOLUM = NOM_TNULL) LEFT OUTER JOIN 
     (SELECT TABLE_NAME AS NOM_TFKS, COUNT(CONSTRAINT_TYPE) AS NumColsFks 
     FROM ALL_CONSTRAINTS 
     WHERE owner = 'PARRANDEROS' AND CONSTRAINT_TYPE = 'R' 
     GROUP BY TABLE_NAME) ON NOM_TCOLUM = NOM_TFKS 
     GROUP BY NOM_TCOLUM, NumColumnas, NumColsNull,NumColsFks  
     ORDER BY NOM_TCOLUM ASC; 