SELECT DISTINCT 'SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = ''PARRANDEROS''
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = ''PARRANDEROS'' AND TC.COLUMN_NAME = ''' || COLUMN_NAME ||
      ''' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;' AS SENTENCIA
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'PARRANDEROS' AND LENGTH(ALL_TAB_COLUMNS.COLUMN_NAME) > 6;

