---ESTE ES EL SCRIPT QUE GENERA LA CONSULTA DEL PUNTO 5
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'ID_BEBEDOR' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'PRESUPUESTO' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'ID_BEBIDA' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'FECHA_ULTIMA_VISITA' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'CANT_SEDES' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'GRADO_ALCOHOL' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;
SELECT TC.COLUMN_NAME AS NOMBRE_COLUMNA, TC.TABLE_NAME AS TABLA_PERTENECIENTE,  COALESCE(CC.CUENTA_REST,0) AS NUM_RESTRICCIONES
FROM ALL_TAB_COLUMNS TC LEFT OUTER JOIN (SELECT COLUMN_NAME, ALL_CONS_COLUMNS.TABLE_NAME,  COUNT(CONSTRAINT_NAME) AS CUENTA_REST
                            FROM ALL_CONS_COLUMNS
                            WHERE owner = 'PARRANDEROS'
                            GROUP BY COLUMN_NAME, TABLE_NAME ) CC ON TC.COLUMN_NAME = CC.COLUMN_NAME
WHERE TC.OWNER = 'PARRANDEROS' AND TC.COLUMN_NAME = 'HORARIO' GROUP BY TC.COLUMN_NAME, TC.TABLE_NAME , CC.CUENTA_REST;