-- Limpieza Base de datos Alohandes

-- USO
-- Copie el contenido deseado de este archivo en una pesta�a SQL de SQL Developer
-- Ejec�telo como un script - Utilice el bot�n correspondiente de la pesta�a utilizada
    
-- Eliminar todas las tablas de la base de datos
DROP TABLE A_ALOJAMIENTO CASCADE CONSTRAINTS;
DROP TABLE A_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE A_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE A_OPERADORUSUARIO CASCADE CONSTRAINTS;
DROP TABLE A_HOTEL CASCADE CONSTRAINTS;
DROP TABLE A_HABITACIONHOTEL CASCADE CONSTRAINTS;
DROP TABLE A_HOSTAL CASCADE CONSTRAINTS;
DROP TABLE A_HABITACIONHOSTAL CASCADE CONSTRAINTS;
DROP TABLE A_VIVIENDAUNIVERSITARIA CASCADE CONSTRAINTS;
DROP TABLE A_HABITACIONVIVIENDAUNIVERSITARIA CASCADE CONSTRAINTS;
DROP TABLE A_VIVIENDATEMPORAL CASCADE CONSTRAINTS;
DROP TABLE A_HABITACIONHUESPED CASCADE CONSTRAINTS;
DROP TABLE A_APARTAMENTOALQUILER CASCADE CONSTRAINTS;
DROP TABLE A_ALOJAMIENTOSERVICIO CASCADE CONSTRAINTS;
DROP TABLE A_RESERVA CASCADE CONSTRAINTS;
COMMIT;

SELECT 'DELETE FROM '  ||table_name|| ';' 
FROM user_tables;

DELETE FROM A_HOTEL;
DELETE FROM A_ALOJAMIENTO;
DELETE FROM A_HABITACIONHOTEL;
DELETE FROM A_CLIENTE;
DELETE FROM A_RESERVA;
DELETE FROM A_ALOJAMIENTOSERVICIO;
DELETE FROM A_APARTAMENTOALQUILER;
DELETE FROM A_HABITACIONHOSTAL;
DELETE FROM A_HABITACIONHUESPED;
DELETE FROM A_HABITACIONVIVIENDAUNIVERSITARIA;
DELETE FROM A_HOSTAL;
DELETE FROM A_OPERADORUSUARIO;
DELETE FROM A_SERVICIO;
DELETE FROM A_VIVIENDATEMPORAL;
DELETE FROM A_VIVIENDAUNIVERSITARIA;
COMMIT;