SELECT COLS.TABLE_NAME AS NOMBRE_TABLA, COLS.COLUMN_NAME AS NOMBRE_COLUMN, COLS.DATA_TYPE AS TIPO_DATO, CONS.CONSTRAINT_NAME AS NOM_RESTRICC
FROM ALL_TAB_COLUMNS COLS LEFT JOIN ALL_CONS_COLUMNS CONS_COLS 
    ON COLS.TABLE_NAME = CONS_COLS.TABLE_NAME AND COLS.OWNER = CONS_COLS.OWNER AND COLS.COLUMN_NAME = CONS_COLS.COLUMN_NAME
    LEFT JOIN ALL_CONSTRAINTS CONS ON CONS_COLS.CONSTRAINT_NAME = CONS.CONSTRAINT_NAME AND CONS_COLS.OWNER = CONS.OWNER
WHERE COLS.OWNER = 'ISIS2304C19202310'
ORDER BY COLS.TABLE_NAME, COLS.COLUMN_NAME;