WITH SEMANAS AS (
  SELECT TO_DATE('01/01/2023', 'DD/MM/YYYY') + ((ROWNUM - 1) * 7) AS SEMANA
  FROM DUAL
  CONNECT BY ROWNUM <= 52
)
SELECT S.SEMANA, COUNT(R.FECHAINI) AS CANTIDAD_RESERVAS,
       MAX(R.NUMOCUPAMIENTO) AS MAX_OCUPACION,
       (SELECT R2.IDALOJAMIENTO
        FROM A_RESERVA R2
        WHERE TRUNC(R2.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
        ORDER BY R2.NUMOCUPAMIENTO DESC
        FETCH FIRST 1 ROW ONLY) AS MAX_ID_ALOJAMIENTO,
        MIN(R.NUMOCUPAMIENTO),
        (SELECT R2.IDALOJAMIENTO
        FROM A_RESERVA R2
        WHERE TRUNC(R2.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
        ORDER BY R2.NUMOCUPAMIENTO ASC
        FETCH FIRST 1 ROW ONLY) AS MIN_ID_ALOJAMIENTO,
        (SELECT COUNT(A5.IDOPERADOR)
        FROM A_RESERVA R5 LEFT JOIN A_ALOJAMIENTO A5 ON R5.IDALOJAMIENTO = A5.ID
        WHERE TRUNC(R5.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
        GROUP BY A5.IDOPERADOR
        ORDER BY COUNT(A5.IDOPERADOR) ASC
        FETCH FIRST 1 ROW ONLY)NUMSOLMIN,
        (SELECT A5.IDOPERADOR
        FROM A_RESERVA R5 LEFT JOIN A_ALOJAMIENTO A5 ON R5.IDALOJAMIENTO = A5.ID
        WHERE TRUNC(R5.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
        GROUP BY A5.IDOPERADOR
        ORDER BY COUNT(A5.IDOPERADOR) ASC
        FETCH FIRST 1 ROW ONLY)OP_MIN_SOLICITADO,
        (SELECT COUNT(A5.IDOPERADOR)
        FROM A_RESERVA R5 LEFT JOIN A_ALOJAMIENTO A5 ON R5.IDALOJAMIENTO = A5.ID
        WHERE TRUNC(R5.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
        GROUP BY A5.IDOPERADOR
        ORDER BY COUNT(A5.IDOPERADOR) DESC
        FETCH FIRST 1 ROW ONLY)NUMSOLMAX,
        (SELECT A5.IDOPERADOR
        FROM A_RESERVA R5 LEFT JOIN A_ALOJAMIENTO A5 ON R5.IDALOJAMIENTO = A5.ID
        WHERE TRUNC(R5.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
        GROUP BY A5.IDOPERADOR
        ORDER BY COUNT(A5.IDOPERADOR) DESC
        FETCH FIRST 1 ROW ONLY)OP_MAX_SOLICITADO
FROM SEMANAS S
LEFT JOIN A_RESERVA R ON TRUNC(R.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
GROUP BY S.SEMANA
ORDER BY S.SEMANA;
