SELECT SEMANA,
       CANTIDAD_RESERVAS,
       MAX(NUMOCUPAMIENTO) KEEP (DENSE_RANK FIRST ORDER BY RANK_MAX_OCUPACION) AS MAX_OCUPACION,
       MAX(IDALOJAMIENTO) KEEP (DENSE_RANK FIRST ORDER BY RANK_MAX_OCUPACION) AS MAX_ID_ALOJAMIENTO,
       MIN(NUMOCUPAMIENTO) KEEP (DENSE_RANK FIRST ORDER BY RANK_MIN_OCUPACION) AS MIN_OCUPACION,
       MIN(IDALOJAMIENTO) KEEP (DENSE_RANK FIRST ORDER BY RANK_MIN_OCUPACION) AS MIN_ID_ALOJAMIENTO,
       MIN(OPERADOR_COUNT) AS NUMSOLMIN,
       MAX(IDOPERADOR) KEEP (DENSE_RANK FIRST ORDER BY OPERADOR_COUNT) AS OP_MIN_SOLICITADO,
       MAX(OPERADOR_COUNT) AS NUMSOLMAX,
       MAX(IDOPERADOR) KEEP (DENSE_RANK LAST ORDER BY OPERADOR_COUNT) AS OP_MAX_SOLICITADO
FROM (
  SELECT S.SEMANA,
         COUNT(R.FECHAINI) OVER (PARTITION BY S.SEMANA) AS CANTIDAD_RESERVAS,
         R.NUMOCUPAMIENTO,
         R.IDALOJAMIENTO,
         A.IDOPERADOR,
         RANK() OVER (PARTITION BY S.SEMANA ORDER BY R.NUMOCUPAMIENTO DESC) AS RANK_MAX_OCUPACION,
         RANK() OVER (PARTITION BY S.SEMANA ORDER BY R.NUMOCUPAMIENTO) AS RANK_MIN_OCUPACION,
         COUNT(A.IDOPERADOR) OVER (PARTITION BY S.SEMANA, A.IDOPERADOR) AS OPERADOR_COUNT
  FROM (
    SELECT TO_DATE('01/01/2022', 'DD/MM/YYYY') + ((ROWNUM - 1) * 7) AS SEMANA
    FROM DUAL
    CONNECT BY ROWNUM <= 52
  ) S
  LEFT JOIN A_RESERVA R ON TRUNC(R.FECHAINI, 'IW') = TRUNC(S.SEMANA, 'IW')
  LEFT JOIN A_ALOJAMIENTO A ON R.IDALOJAMIENTO = A.ID
)
GROUP BY SEMANA, CANTIDAD_RESERVAS
ORDER BY SEMANA;