-- RFC1 | MOSTRAR EL DINERO RECIBIDO POR CADA PROVEEDOR DE ALOJAMIENTO DURANTE EL AÑO ACTUAL Y EL AÑO CORRIDO
SELECT ID_PROVEEDOR, DINERO_RECIBIDO_ANIO_ACTUAL, DINERO_RECIBIDO_ANIO_CORRIDO
FROM (
  SELECT ID_PROVEEDOR,
         SUM(CASE WHEN A_RESERVA.FECHAINI >= TRUNC(SYSDATE, 'YEAR') AND A_RESERVA.FECHAINI < ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'), 12)
                  THEN COSTO ELSE 0 END) AS DINERO_RECIBIDO_ANIO_ACTUAL,
         SUM(CASE WHEN A_RESERVA.FECHAINI >= ADD_MONTHS(SYSDATE, -12) AND A_RESERVA.FECHAINI < SYSDATE
                  THEN COSTO ELSE 0 END) AS DINERO_RECIBIDO_ANIO_CORRIDO
  FROM (
    SELECT A_ALOJAMIENTO.ID, 
           COALESCE(A_HABITACIONHOTEL.IDHOTEL, A_HABITACIONHOSTAL.IDHOSTAL, A_HABITACIONVIVIENDAUNIVERSITARIA.IDVIVIENDAUNIVERSITARIA,
                    A_HABITACIONHUESPED.IDENTIFICACIONOPERADORUSUARIO, A_VIVIENDATEMPORAL.IDENTIFICACIONOPERADORUSUARIO, A_APARTAMENTOALQUILER.IDENTIFICACIONOPERADORUSUARIO) AS ID_PROVEEDOR,
           A_ALOJAMIENTO.COSTO
    FROM A_ALOJAMIENTO
    LEFT JOIN A_HABITACIONHOTEL ON A_ALOJAMIENTO.ID = A_HABITACIONHOTEL.ID
    LEFT JOIN A_HABITACIONHOSTAL ON A_ALOJAMIENTO.ID = A_HABITACIONHOSTAL.ID
    LEFT JOIN A_HABITACIONVIVIENDAUNIVERSITARIA ON A_ALOJAMIENTO.ID = A_HABITACIONVIVIENDAUNIVERSITARIA.ID
    LEFT JOIN A_HABITACIONHUESPED ON A_ALOJAMIENTO.ID = A_HABITACIONHUESPED.IDALOJAMIENTO
    LEFT JOIN A_VIVIENDATEMPORAL ON A_ALOJAMIENTO.ID = A_VIVIENDATEMPORAL.IDALOJAMIENTO
    LEFT JOIN A_APARTAMENTOALQUILER ON A_ALOJAMIENTO.ID = A_APARTAMENTOALQUILER.IDALOJAMIENTO
  ) AP
  JOIN A_RESERVA ON AP.ID = A_RESERVA.IDALOJAMIENTO
  GROUP BY ID_PROVEEDOR
) GANANCIAS
ORDER BY ID_PROVEEDOR;