SELECT A_CLIENTE.IDENTIFICACION IDENTIFICACION,
A_CLIENTE.NOMBRE NOMBRE,
A_CLIENTE.TIPOVINCULO TIPOVINCULO,
A_CLIENTE.CORREOELECTRONICO CORREOELECTRONICO,
A_CLIENTE.TELEFONO TELEFONO,
A_RESERVA.ID ID
FROM A_CLIENTE LEFT JOIN A_RESERVA ON A_CLIENTE.IDENTIFICACION = A_RESERVA.IDENTIFICACIONCLIENTE
WHERE A_RESERVA.IDENTIFICACIONCLIENTE IS NULL
GROUP BY A_CLIENTE.IDENTIFICACION ,
A_CLIENTE.NOMBRE ,
A_CLIENTE.TIPOVINCULO ,
A_CLIENTE.CORREOELECTRONICO ,
A_CLIENTE.TELEFONO ,
A_RESERVA.ID
ORDER BY A_CLIENTE.IDENTIFICACION;


SELECT A_CLIENTE.IDENTIFICACION IDENTIFICACION,
A_CLIENTE.NOMBRE NOMBRE,
A_CLIENTE.TIPOVINCULO TIPOVINCULO,
A_CLIENTE.CORREOELECTRONICO CORREOELECTRONICO,
A_CLIENTE.TELEFONO TELEFONO,
A_RESERVA.ID ID
FROM A_CLIENTE LEFT JOIN A_RESERVA ON A_CLIENTE.IDENTIFICACION = A_RESERVA.IDENTIFICACIONCLIENTE
WHERE A_RESERVA.IDENTIFICACIONCLIENTE IS NULL
GROUP BY A_CLIENTE.IDENTIFICACION ,
A_CLIENTE.NOMBRE ,
A_CLIENTE.TIPOVINCULO ,
A_CLIENTE.CORREOELECTRONICO ,
A_CLIENTE.TELEFONO ,
A_RESERVA.ID
ORDER BY ?;