-- RFC3 | MOSTRAR EL ÍNDICE DE OCUPACIÓN DE CADA UNA DE LAS OFERTAS DE ALOJAMIENTO REGISTRADAS
SELECT A.ID, A.UBICACION, NVL(RA.DIAS_RESERVADOS, 0) AS DIAS_RESERVADOS, ROUND((NVL(RA.DIAS_RESERVADOS, 0) / 365) * 100, 2) AS INDICE_OCUPACION
FROM A_ALOJAMIENTO A LEFT JOIN ( SELECT IDALOJAMIENTO, SUM(FECHAFIN - FECHAINI) AS DIAS_RESERVADOS FROM A_RESERVA
                                 HAVING SUM(FECHAFIN - FECHAINI)<=365
                                 GROUP BY IDALOJAMIENTO ) RA ON A.ID = RA.IDALOJAMIENTO
ORDER BY A.ID;