SELECT A_CLIENTE.IDENTIFICACION, COALESCE(A_RESERVA.FECHAFIN - A_RESERVA.FECHAINI,0) DIAS_R, A_RESERVA.IDALOJAMIENTO, A_RESERVA.GANANCIA DINERO_PAGADO, A_ALOJAMIENTO.TIPOALOJAMIENTO, LISTAGG(A_SERVICIO.TIPO, ',') SERVICIOS
FROM (((A_CLIENTE LEFT JOIN A_RESERVA ON A_RESERVA.IDENTIFICACIONCLIENTE = A_CLIENTE.IDENTIFICACION) 
     LEFT JOIN A_ALOJAMIENTO ON A_ALOJAMIENTO.ID = A_RESERVA.IDALOJAMIENTO)
     LEFT JOIN A_ALOJAMIENTOSERVICIO ON A_ALOJAMIENTOSERVICIO.IDALOJAMIENTO = A_RESERVA.IDALOJAMIENTO)
     LEFT JOIN A_SERVICIO ON A_SERVICIO.ID = A_ALOJAMIENTOSERVICIO.IDSERVICIO
WHERE A_CLIENTE.IDENTIFICACION = 1
GROUP BY A_CLIENTE.IDENTIFICACION, A_RESERVA.FECHAFIN - A_RESERVA.FECHAINI,A_RESERVA.IDALOJAMIENTO, A_RESERVA.GANANCIA, A_ALOJAMIENTO.TIPOALOJAMIENTO;