-- RFC2 | MOSTRAR LAS 20 OFERTAS MÁS POPULARES
SELECT A_ALOJAMIENTO.ID, A_ALOJAMIENTO.UBICACION, A_ALOJAMIENTO.DURACIONMIN, A_ALOJAMIENTO.COSTO, COUNT(A_RESERVA.IDALOJAMIENTO) AS TOTAL_RESERVAS
FROM A_ALOJAMIENTO
JOIN A_RESERVA ON A_ALOJAMIENTO.ID = A_RESERVA.IDALOJAMIENTO
GROUP BY A_ALOJAMIENTO.ID, A_ALOJAMIENTO.UBICACION, A_ALOJAMIENTO.DURACIONMIN, A_ALOJAMIENTO.COSTO
ORDER BY TOTAL_RESERVAS DESC
FETCH FIRST 20 ROWS ONLY;