ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT BARES.CIUDAD, COUNT(BARES.NOMBRE) AS NUM_BARES_QUE_SIRVEN
FROM BARES, SIRVEN, BEBIDAS
WHERE BARES.ID = SIRVEN.ID_BAR 
    AND BEBIDAS.ID = SIRVEN.ID_BEBIDA
    AND BEBIDAS.GRADO_ALCOHOL BETWEEN 8 AND 12
    AND BEBIDAS.TIPO = 1
GROUP BY BARES.CIUDAD
ORDER BY NUM_BARES_QUE_SIRVEN DESC
FETCH FIRST 1 ROWS ONLY;