ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT BEBEDOR_ID, NOMBRE_BEBEDOR, CIUDAD_BEBEDOR, CUENTA_BEBEDORES+CUENTA_FRECUENTAN+CUENTA_GUSTAN AS CUENTA_TOTAL
FROM (SELECT BEBEDORES.ID AS BEBEDOR_ID, BEBEDORES.NOMBRE AS NOMBRE_BEBEDOR, BEBEDORES.CIUDAD AS CIUDAD_BEBEDOR, COUNT(BEBEDORES.ID) AS CUENTA_BEBEDORES
        FROM BEBEDORES
        GROUP BY BEBEDORES.ID, BEBEDORES.NOMBRE, BEBEDORES.CIUDAD),
     (SELECT FRECUENTAN.ID_BEBEDOR AS FRECUENTAN_BEBEDOR_ID, COUNT(FRECUENTAN.ID_BEBEDOR) AS CUENTA_FRECUENTAN
        FROM FRECUENTAN
        GROUP BY FRECUENTAN.ID_BEBEDOR),
     (SELECT GUSTAN.ID_BEBEDOR AS GUSTAN_BEBEDOR_ID, COUNT(GUSTAN.ID_BEBEDOR) AS CUENTA_GUSTAN
        FROM GUSTAN
        GROUP BY GUSTAN.ID_BEBEDOR)
WHERE BEBEDOR_ID = FRECUENTAN_BEBEDOR_ID AND BEBEDOR_ID = GUSTAN_BEBEDOR_ID
ORDER BY CUENTA_TOTAL DESC, CIUDAD_BEBEDOR DESC
FETCH FIRST 10 ROWS ONLY;