ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

SELECT TABLA_MAX_FORANEOS.*, TABLA_CUENTA_BEBEDORES.MEJOR_HORARIO
FROM(SELECT ID_BAR, NOMBRE_BAR, MAX(CONTADOR_FORANEOS) AS MAX_CONTADOR_FORANEOS
    FROM(SELECT ID_BAR, NOMBRE_BAR, MEJOR_HORARIO, COUNT(BEBEDOR_ID) AS CONTADOR_FORANEOS
        FROM(SELECT BARES.ID AS ID_BAR, BARES.NOMBRE AS NOMBRE_BAR, FRECUENTAN.HORARIO AS MEJOR_HORARIO, BEBIDAS.NOMBRE AS BEBIDA_ELEGIDA, BEBEDORES.ID AS BEBEDOR_ID
            FROM FRECUENTAN, BARES, BEBEDORES, GUSTAN, BEBIDAS, TIPO_BEBIDA
            WHERE BEBEDORES.CIUDAD <> BARES.CIUDAD 
                AND FRECUENTAN.ID_BEBEDOR = BEBEDORES.ID 
                AND ID_BAR = BARES.ID 
                AND GUSTAN.ID_BEBEDOR = FRECUENTAN.ID_BEBEDOR
                AND BEBIDAS.ID = GUSTAN.ID_BEBIDA
                AND BEBIDAS.TIPO = TIPO_BEBIDA.ID
                AND TIPO_BEBIDA.NOMBRE = 'gaseosa'
            GROUP BY BARES.ID, BARES.NOMBRE , FRECUENTAN.HORARIO, BEBIDAS.NOMBRE, BEBEDORES.ID) 
        GROUP BY ID_BAR, NOMBRE_BAR, MEJOR_HORARIO)
    GROUP BY ID_BAR,NOMBRE_BAR) TABLA_MAX_FORANEOS
    ,
    (SELECT ID_BAR, NOMBRE_BAR, MEJOR_HORARIO, COUNT(BEBEDOR_ID) AS CONTADOR_FORANEOS
    FROM(SELECT BARES.ID AS ID_BAR ,BARES.NOMBRE AS NOMBRE_BAR, FRECUENTAN.HORARIO AS MEJOR_HORARIO, BEBIDAS.NOMBRE AS BEBIDA_ELEGIDA, BEBEDORES.ID AS BEBEDOR_ID
        FROM FRECUENTAN, BARES, BEBEDORES, GUSTAN, BEBIDAS, TIPO_BEBIDA
        WHERE BEBEDORES.CIUDAD <> BARES.CIUDAD 
            AND FRECUENTAN.ID_BEBEDOR = BEBEDORES.ID 
            AND ID_BAR = BARES.ID 
            AND GUSTAN.ID_BEBEDOR = FRECUENTAN.ID_BEBEDOR
            AND BEBIDAS.ID = GUSTAN.ID_BEBIDA
            AND BEBIDAS.TIPO = TIPO_BEBIDA.ID
            AND TIPO_BEBIDA.NOMBRE = 'gaseosa'
        GROUP BY BARES.ID, BARES.NOMBRE , FRECUENTAN.HORARIO, BEBIDAS.NOMBRE, BEBEDORES.ID) 
    GROUP BY ID_BAR, NOMBRE_BAR, MEJOR_HORARIO) TABLA_CUENTA_BEBEDORES
WHERE TABLA_MAX_FORANEOS.NOMBRE_BAR = TABLA_CUENTA_BEBEDORES.NOMBRE_BAR AND TABLA_MAX_FORANEOS.MAX_CONTADOR_FORANEOS = TABLA_CUENTA_BEBEDORES.CONTADOR_FORANEOS 
ORDER BY TABLA_MAX_FORANEOS.NOMBRE_BAR ASC;