ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;

ALTER SESSION SET CURRENT_SCHEMA = PARRANDEROS;
SELECT GUSTAN.ID_BEBIDA, BEBIDAS.nombre, TIPO_BEBIDA.nombre
FROM BARES
JOIN FRECUENTAN ON FRECUENTAN.id_bar = BARES.id
JOIN BEBEDORES ON BEBEDORES.id = FRECUENTAN.id_bebedor
JOIN GUSTAN ON GUSTAN.id_bebedor = BEBEDORES.id
JOIN BEBIDAS ON BEBIDAS.id = GUSTAN.id_bebida
JOIN TIPO_BEBIDA ON TIPO_BEBIDA.id = BEBIDAS.tipo
WHERE FRECUENTAN.ID_BAR = BARES.ID 
    AND FRECUENTAN.ID_BEBEDOR = BEBEDORES.ID
    AND FRECUENTAN.ID_BEBEDOR = GUSTAN.ID_BEBEDOR
GROUP BY GUSTAN.ID_BEBIDA, BEBIDAS.nombre, TIPO_BEBIDA.nombre
HAVING COUNT(CASE WHEN BEBEDORES.CIUDAD <> BARES.CIUDAD THEN 1 END) > COUNT(CASE WHEN BEBEDORES.CIUDAD = BARES.CIUDAD THEN 1 END)
ORDER BY COUNT(BEBEDORES.ID) DESC
FETCH FIRST 10 ROWS ONLY;